site_name: PY_REPORT
site_author: tro
site_url: https://python-report.com
site_description: Report on completed laboratory work
repo_url: https://github.com/miroT1/MIRON/
edit_uri: ""

docs_dir: site
site_dir: docs


theme:
    name: material
    next_previous: false


nav:
  - Главная: index.md
  - Автор: author.md
  - Лабораторные ИТМО:
    - Лабораторная 1: lub_12.md
    - Лабораторная 2: lub_13.md
    - Лабораторная 3: lub_14.md
    - Лабораторная 4: lub_15.md
    - Лабораторная 5: lub_16.md





